### ISSUE TITLE
no new release

### ISSUE THREAD

**Issue by Dushku** [RedHatter/Graveyard#23]
Github noob here. It would appear that Graveyard has been updated to include Bloodreaver Gul'Dan. However, on the releases page, it shows the latest release was back in April.

Also, there's been no acknowledgement of the fact that the N'Zoth counter (previously?) doesn't account for minions that began as Shadow Reflection, even though N'Zoth WILL rez them.

**Comment by chWolfgang** [comment]
I would like to second what Dushku said.
I would really like to get the update or is there a way to install the new commits my self?
Thanks for all the work on this.

**Comment by Dushku** [comment]
For those with this issue, judge2020 has released an update that is compatible with the latest HDT (that broke Graveyard's Settings functionality) here: https://github.com/RedHatter/Graveyard/pull/26
