### ISSUE TITLE
Checking in

### ISSUE THREAD

**Issue by chWolfgang** [RedHatter/Graveyard#37]
Greetings!
I love this add-on. It makes my favorite style of decks much more enjoyable. I am am hoping (wondering) if this is still being supported/developed? I know this is a "labor of love" and as such there is no obligation to continue to support it.

I wanted to stop by and issue a word of thank you and encouragement to keep this project moving forward.

**Comment by RedHatter** [comment]
The project is not "dead" but I don't have the time to completely support it. It's one of those projects I made in a weekend and I don't have much time to work on. I try to find time now and then but it's not really a priority.
