### ISSUE TITLE
New Card: Nine Lives

### ISSUE THREAD

**Issue by chWolfgang** [RedHatter/Graveyard#42]
Anyone around to add the RoS card: Nine Lives and/or a list for DeathRattle minions?

I love this add-on. Thanks!

**Comment by Supergecki** [comment]
Nine Lives is coming, I've already made a pull request.
It then should track all deathrattle minions that died.

**Comment by chWolfgang** [comment]
That is great news. TYVM. 
Question, every time HSDT patches, I loose my settings for Graveyard. Do you know if there is a way to fix that?
Thanks for your time!

**Comment by Supergecki** [comment]
You're welcome.
I'm sorry, I found it also really annoying but don't know how to do it.
I think it may be because HSDT overwrites the plugin's user configs with every patch.
Don't know how to avoid it.

**Comment by Supergecki** [comment]
I looked it up.
Other plugins (like [Packtracker](https://github.com/MGK82/PackTracker)) don't store their settings in their own directories but in a new directory (somewhere like ".../AppData/Roaming/HearthstoneDeckTracker/Packtracker" on Windows). It would take a lot of time and work to make the program save the settings in such a directory and grab the values from there. But this should save the problem.
