### ISSUE TITLE
New version download?

### ISSUE THREAD

**Issue by chWolfgang** [RedHatter/Graveyard#47]
Should the new version (merged today) be on the download page? Or am I missing something?
Thanks everyone for keep this moving.

**Comment by Supergecki** [comment]
No, RedHatter would have to tag the pull request to let the version appear on the download page.
I thought I already uploaded this version once, but here it is:
[Graveyard.zip](https://github.com/RedHatter/Graveyard/files/3547398/Graveyard.zip)

You're welcome.
