### ISSUE TITLE
Suggestion/Request - Lady Liadrin

### ISSUE THREAD

**Issue by Mannichon** [RedHatter/Graveyard#57]
Maybe I'm dumb and there is already somethin that can track this, or another plugin, or mayeb i'm the only one who needs it, but- 
A tracker for Lady Liadrin would be super handy.
Idk much about coding, so maybe it would be harder than it sounds, but it would just be nice to know what cards(or even better, what buffs) i've played on my minions. I love this plugin when i play Gul'Dan or Ebonlocke, because I know what to expect. But when playing Lady Liadrin i get annoyed because it seems like despite all these trackers i have open, none seem to bother to track what spells/buffs i've played. It just takes it out of my decklist, which is handy unless i play the same spell multiple times, as I do with most Librams.

Thank you so much for this plugin, and thank you for your time and consideration.

**Comment by joc256** [comment]
try https://github.com/batstyx/Graveyard/releases

**Comment by Ririshi** [comment]
I think https://github.com/RedHatter/Graveyard/pull/60 the Lady Liadrin mechanic.
