### ISSUE TITLE
Doesn't reset opponent graveyard when game is over.

### ISSUE THREAD

**Issue by zackmorgs** [RedHatter/Graveyard#7]
See title. I'm seeing stuff from my previous games only way I can fix it is resetting it before each game.

**Comment by menace97** [comment]
i agree, this would be a nice change.

this is probably similar if not the same issue as issue#6
[https://github.com/RedHatter/Graveyard/issues/6](url)

**Comment by GuntherScuhlz** [comment]
Don't need to restart HDT, just disable an re-enable plugin.
A proper fix would be nice, though :)
