### ISSUE TITLE
Suggestion: Options for changing position, scale and opacity

### ISSUE THREAD

**Issue by menace97** [RedHatter/Graveyard#8]
Similar to options in **HDT**, in the **Overlay > Player** section of the **Options** - 
adding options to change the **position** (location), **scale** (%) and maybe **opacity** (%) would be helpful.

With so many "**Highlander**" type decks with only _one of each card_ (the popularity of **Reno Jackson** in decks) the minion graveyard list can get quite long. I've noticed occasionally when the list gets long, it can obscure the "**End Turn**" button, making it difficult to click to end the turn.

Being able to re-position and/or scale the graveyard list might be an option to overcome this.

_Thanks for your fantastic plugin @RedHatter ! :)_

**Comment by lukasani94** [comment]
Agreed

**Comment by pagem** [comment]
If not the ability to move, resize or make the window opaque could you add the functionality for the window with the creature lists to autohide or be minimised? Autohide would be great and then reshow on some user action like a mouseover.

**Comment by socopithy** [comment]
Bumping this for support of the suggestion.

The default 110 scale of Graveyard windows makes quite the clutter :(

Is there any plan to add scaling at least?
Thanks for the work on this plugin.

**Comment by dschnitzel** [comment]
Bumping for some feedback on this situation.
This plugin is a great addition to HDT but without the scaling option its almost un-usable. Please get back to us and let us know if you continue to work on this project, and if this is something you are planing to implement.

And like everyone else  _thanks for the amazing plugin♥ @RedHatter _
